# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_grandpa',
            new_name='requires_assistant',
        ),
    ]
