# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import translator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HasSocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('input', 'Recibidos'), ('output', 'Enviados')], max_length=6)),
                ('content', models.TextField(null=True)),
                ('file', models.FileField(null=True, upload_to=translator.models.user_directory_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('shortName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('users', models.ManyToManyField(through='translator.HasSocialNetwork', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='through',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translator.SocialNetwork'),
        ),
        migrations.AddField(
            model_name='message',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hassocialnetwork',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translator.SocialNetwork'),
        ),
        migrations.AddField(
            model_name='hassocialnetwork',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hassocialnetwork',
            unique_together=set([('social', 'username'), ('user', 'social')]),
        ),
    ]
