# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_hassocialnetwork_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hassocialnetwork',
            name='alias',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
