# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0003_auto_20171120_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('input', 'Recibido'), ('output', 'Enviado')], max_length=6),
        ),
    ]
