# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0004_auto_20171121_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='hassocialnetwork',
            name='saveIncome',
            field=models.BooleanField(default=False),
        ),
    ]
