# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0007_interactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionlog',
            name='final_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='media',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Imagen'), ('text', 'Texto'), ('videocall', 'Videollamada')], max_length=10),
        ),
    ]
