# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0010_socialnetwork_pushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sourceID',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
